### ISSUE TITLE
Border color of the last tabs, when adding more than four Tabs

### ISSUE THREAD

**Issue by lucaandaloro** [nhatlang19/toggle_bar_button#1]
In the toggle_bar_button.dart file on line 156, the "`color:`" parameter should not be `Colors.amber [500] `but it should be `this._borderColor`
![Schermata 2020-03-06 alle 10 50 12](https://user-images.githubusercontent.com/32513836/76072449-483f5800-5f98-11ea-9b51-68a2f939fb42.png)

**Comment by nhatlang19** [comment]
Thanks for your feedback. 

Fixed
